// =====================================================
// DATOS DE LOS 30 MUNICIPIOS DEL DEPARTAMENTO DE ORURO
// =====================================================

export const municipios = [
  // ─── ORURO (capital) ───────────────────────────────
  {
    slug: 'oruro',
    nombre: 'Oruro',
    gentilicio: 'Orureño/a',
    descripcion: 'Capital del Departamento de Oruro, reconocida mundialmente por su Carnaval declarado Patrimonio Cultural Inmaterial de la Humanidad por la UNESCO. Centro histórico, cultural y minero de Bolivia.',
    esCapital: true,
    poblacion: '302,643',
    anoCenso: 2012,
    rankingDep: '1°',
    altitud: 3697,
    lat: -17.9667,
    lng: -67.1167,
    latStr: "17° 58' 0'' Sur",
    lngStr: "67° 7' 0'' Oeste",
    codigo: '040101',
    provincia: 'Cercado',
    alcalde: 'Adhermar Wilcarani Morales',
    partido: 'MAS-IPSP',
    direccion: 'Plaza 10 de Febrero, Acera Sur',
    telefono: '67202855',
    web: 'oruro.org.bo',
    ciudadesHermanadas: [{ flag: '🇵🇪', ciudad: 'Lima, Perú' }, { flag: '🇺🇸', ciudad: 'Salt Lake City, EE.UU.' }],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza', dist: 'Local' },
      { nombre: 'Aerop. Internacional Jorge Wilstermann', dist: '116.7 km' },
      { nombre: 'Aerop. Internacional de El Alto', dist: '198.1 km' },
    ],
    vecinos: [
      { nombre: 'Soracachi', dist: '23.7 km' }, { nombre: 'Machacamarca', dist: '25 km' },
      { nombre: 'Poopó', dist: '27 km' }, { nombre: 'Caracollo', dist: '36.8 km' },
      { nombre: 'Toledo', dist: '40.5 km' }, { nombre: 'El Choro', dist: '43.7 km' },
      { nombre: 'Huanuni', dist: '46 km' },
    ],
    distancias: [
      { nombre: 'Quillacollo', km: '109 km', closest: true }, { nombre: 'Cochabamba', km: '120 km' },
      { nombre: 'Sacaba', km: '130 km' }, { nombre: 'El Alto', km: '197 km' },
      { nombre: 'Sucre', km: '230 km' }, { nombre: 'Potosí', km: '231 km' },
      { nombre: 'Santa Cruz', km: '416 km' }, { nombre: 'Trinidad', km: '422 km' },
    ],
    idiomas: [
      { lang: 'Aymara', name: 'Ururu' }, { lang: 'Quechua', name: 'Uru Uru suyu' },
      { lang: 'Japonés', name: 'オルロ' }, { lang: 'Ruso', name: 'Оруро' },
      { lang: 'Chino', name: '奥鲁罗省' }, { lang: 'Coreano', name: '오루로' },
    ],
  },

  // ─── CHALLAPATA ────────────────────────────────────
  {
    slug: 'challapata',
    nombre: 'Challapata',
    gentilicio: 'Challapateño/a',
    descripcion: 'Municipio localizado en la Provincia Eduardo Abaroa, importante centro comercial y de tránsito en el altiplano sur del Departamento de Oruro.',
    esCapital: false,
    poblacion: '28,304',
    anoCenso: 2012,
    rankingDep: '2°',
    altitud: 3718,
    lat: -18.9,
    lng: -66.7667,
    latStr: "18° 54' 0'' Sur",
    lngStr: "66° 46' 0'' Oeste",
    codigo: '040201',
    provincia: 'Eduardo Abaroa',
    alcalde: 'Marcos Choqueticlla Tito',
    partido: 'MAS-IPSP',
    direccion: 'Plaza Eduardo Avaroa, Esq. Av. Mariano Baptista',
    telefono: '72341451',
    web: 'challapata.gob.bo',
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza', dist: '109.4 km' },
      { nombre: 'Aerop. Capitão Nicolas Rojas', dist: '130.9 km' },
      { nombre: 'Aerop. Internacional Juana Azurduy de Padilla', dist: '156 km' },
    ],
    vecinos: [
      { nombre: 'Huari', dist: '12.5 km' }, { nombre: 'Urmiri', dist: '37.6 km' },
      { nombre: 'Pazña', dist: '37.7 km' }, { nombre: 'Santuario de Quillacas', dist: '41.7 km' },
      { nombre: 'Pampa Aullagas', dist: '44 km' }, { nombre: 'Antequera', dist: '47.7 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '110 km', closest: true }, { nombre: 'Sucre', km: '160 km' },
      { nombre: 'Potosí', km: '131 km' }, { nombre: 'Cochabamba', km: '180 km' },
      { nombre: 'Quillacollo', km: '175 km' }, { nombre: 'Santa Cruz', km: '397 km' },
      { nombre: 'El Alto', km: '305 km' }, { nombre: 'Tarija', km: '362 km' },
    ],
    idiomas: [{ lang: 'Chino', name: '查亞帕塔' }],
  },

  // ─── HUANUNI ───────────────────────────────────────
  {
    slug: 'huanuni',
    nombre: 'Huanuni',
    gentilicio: 'Huanuneño/a',
    descripcion: 'Municipio minero de la Provincia Pantaleón Dalence, famoso por sus yacimientos de estaño. Uno de los centros mineros más importantes de Bolivia y del Departamento de Oruro.',
    esCapital: false,
    poblacion: '24,677',
    anoCenso: 2012,
    rankingDep: '3°',
    altitud: 3951,
    lat: -18.29,
    lng: -66.8381,
    latStr: "18° 17' 24'' Sur",
    lngStr: "66° 50' 17'' Oeste",
    codigo: '040701',
    provincia: 'Pantaleón Dalence',
    alcalde: 'Ever Colque Yucra',
    partido: 'MTS',
    direccion: 'Plaza Principal Fermín López',
    telefono: '72308728',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza', dist: '44.3 km' },
      { nombre: 'Aerop. Internacional Jorge Wilstermann', dist: '119.5 km' },
      { nombre: 'Aerop. Internacional Juana Azurduy de Padilla', dist: '181.8 km' },
    ],
    vecinos: [
      { nombre: 'Antequera', dist: '21 km' }, { nombre: 'Machacamarca', dist: '23.3 km' },
      { nombre: 'Poopó', dist: '26.2 km' }, { nombre: 'Llallagua', dist: '29.8 km' },
      { nombre: 'El Choro', dist: '30.2 km' }, { nombre: 'Urmiri', dist: '32.5 km' },
      { nombre: 'Pazña', dist: '35.1 km' }, { nombre: 'Oruro', dist: '46 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '47 km', closest: true }, { nombre: 'Cochabamba', km: '123 km' },
      { nombre: 'Potosí', km: '184 km' }, { nombre: 'Sucre', km: '187 km' },
      { nombre: 'El Alto', km: '244 km' }, { nombre: 'Santa Cruz', km: '389 km' },
      { nombre: 'Trinidad', km: '437 km' }, { nombre: 'Tarija', km: '423 km' },
    ],
    idiomas: [{ lang: 'Japonés', name: 'ワヌニ' }, { lang: 'Chino', name: '瓦努尼' }],
  },

  // ─── CARACOLLO ─────────────────────────────────────
  {
    slug: 'caracollo',
    nombre: 'Caracollo',
    gentilicio: 'Caracolleño/a',
    descripcion: 'Municipio de la Provincia Cercado, ubicado en el corredor principal de la carretera La Paz-Oruro. Importante nodo de comunicaciones y comercio del altiplano boliviano.',
    esCapital: false,
    poblacion: '13,582',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3780,
    lat: -17.6503,
    lng: -67.2183,
    latStr: "17° 39' Sur",
    lngStr: "67° 13' Oeste",
    codigo: '040102',
    provincia: 'Cercado',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Caracollo',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza', dist: '37 km' },
      { nombre: 'Aerop. Internacional de El Alto', dist: '170 km' },
    ],
    vecinos: [
      { nombre: 'Oruro', dist: '36.8 km' }, { nombre: 'Toledo', dist: '38 km' },
      { nombre: 'El Choro', dist: '40 km' }, { nombre: 'Soracachi', dist: '45 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '37 km', closest: true }, { nombre: 'La Paz', km: '170 km' },
      { nombre: 'Cochabamba', km: '130 km' }, { nombre: 'Potosí', km: '270 km' },
    ],
    idiomas: [],
  },

  // ─── HUARI ─────────────────────────────────────────
  {
    slug: 'huari',
    nombre: 'Huari',
    gentilicio: 'Hureño/a',
    descripcion: 'Capital de la Provincia Eduardo Abaroa, famosa por la cerveza Huari, una de las más consumidas en Bolivia. Centro agropecuario e industrial del sur del departamento.',
    esCapital: false,
    poblacion: '11,750',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3680,
    lat: -18.9933,
    lng: -66.8417,
    latStr: "18° 59' Sur",
    lngStr: "66° 50' Oeste",
    codigo: '040202',
    provincia: 'Eduardo Abaroa',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Huari',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aerop. Capitão Nicolas Rojas (Potosí)', dist: '120 km' },
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '130 km' },
    ],
    vecinos: [
      { nombre: 'Challapata', dist: '12.5 km' }, { nombre: 'Pazña', dist: '30 km' },
      { nombre: 'Poopó', dist: '45 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '120 km', closest: true }, { nombre: 'Potosí', km: '115 km' },
      { nombre: 'Cochabamba', km: '200 km' }, { nombre: 'Sucre', km: '175 km' },
    ],
    idiomas: [],
  },

  // ─── TOTORA (ORURO) ────────────────────────────────
  {
    slug: 'totora',
    nombre: 'Totora',
    gentilicio: 'Totoreño/a',
    descripcion: 'Municipio de la Provincia Cercado, localizado al norte del departamento de Oruro. Comunidad agrícola del altiplano boliviano con rica tradición cultural aymara.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3800,
    lat: -17.3,
    lng: -67.4,
    latStr: "17° 18' Sur",
    lngStr: "67° 24' Oeste",
    codigo: '040103',
    provincia: 'Cercado',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Totora',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '60 km' },
    ],
    vecinos: [
      { nombre: 'Caracollo', dist: '30 km' }, { nombre: 'Toledo', dist: '25 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '55 km', closest: true }, { nombre: 'La Paz', km: '200 km' },
    ],
    idiomas: [],
  },

  // ─── SALINAS DE GARCI MENDOZA ──────────────────────
  {
    slug: 'salinas-de-garci-mendoza',
    nombre: 'Salinas de Garci Mendoza',
    gentilicio: 'Salinero/a',
    descripcion: 'Municipio de la Provincia Ladislao Cabrera, ubicado en las orillas del Salar de Coipasa. Puerta de entrada a los salares del sur del Departamento de Oruro.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3700,
    lat: -19.6333,
    lng: -67.6667,
    latStr: "19° 38' Sur",
    lngStr: "67° 40' Oeste",
    codigo: '041101',
    provincia: 'Ladislao Cabrera',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Salinas de Garci Mendoza',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '220 km' },
    ],
    vecinos: [
      { nombre: 'Pampa Aullagas', dist: '45 km' }, { nombre: 'Coipasa', dist: '80 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '220 km', closest: true }, { nombre: 'Uyuni', km: '130 km' },
    ],
    idiomas: [],
  },

  // ─── TOLEDO ────────────────────────────────────────
  {
    slug: 'toledo',
    nombre: 'Toledo',
    gentilicio: 'Toledano/a',
    descripcion: 'Municipio de la Provincia Saucarí. Localidad agrícola y ganadera del altiplano orureño, conocida por sus tradiciones culturales y festividades patronales.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3710,
    lat: -17.9667,
    lng: -67.4167,
    latStr: "17° 58' Sur",
    lngStr: "67° 25' Oeste",
    codigo: '040501',
    provincia: 'Saucarí',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Toledo',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '43 km' },
    ],
    vecinos: [
      { nombre: 'Oruro', dist: '40.5 km' }, { nombre: 'Caracollo', dist: '38 km' },
      { nombre: 'El Choro', dist: '30 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '41 km', closest: true }, { nombre: 'Cochabamba', km: '155 km' },
    ],
    idiomas: [],
  },

  // ─── CORQUE ────────────────────────────────────────
  {
    slug: 'corque',
    nombre: 'Corque',
    gentilicio: 'Corqueño/a',
    descripcion: 'Capital de la Provincia Carangas, municipio en el altiplano occidental del Departamento de Oruro. Centro administrativo y cultural de la región de Carangas.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3770,
    lat: -18.35,
    lng: -67.8833,
    latStr: "18° 21' Sur",
    lngStr: "67° 53' Oeste",
    codigo: '040601',
    provincia: 'Carangas',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Corque',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '110 km' },
    ],
    vecinos: [
      { nombre: 'Turco', dist: '45 km' }, { nombre: 'Curahuara de Carangas', dist: '50 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '110 km', closest: true }, { nombre: 'La Paz', km: '250 km' },
    ],
    idiomas: [],
  },

  // ─── EL CHORO ──────────────────────────────────────
  {
    slug: 'el-choro',
    nombre: 'El Choro',
    gentilicio: 'Choreño/a',
    descripcion: 'Municipio de la Provincia Cercado, comunidad agrícola aymara al norte del Departamento de Oruro. Conocido por sus tradiciones y actividades pecuarias en el altiplano.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3720,
    lat: -17.8,
    lng: -67.3,
    latStr: "17° 48' Sur",
    lngStr: "67° 18' Oeste",
    codigo: '040104',
    provincia: 'Cercado',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de El Choro',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '46 km' },
    ],
    vecinos: [
      { nombre: 'Oruro', dist: '43.7 km' }, { nombre: 'Caracollo', dist: '40 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '44 km', closest: true }, { nombre: 'Cochabamba', km: '145 km' },
    ],
    idiomas: [],
  },

  // ─── SABAYA ────────────────────────────────────────
  {
    slug: 'sabaya',
    nombre: 'Sabaya',
    gentilicio: 'Sabayeño/a',
    descripcion: 'Municipio de la Provincia Sabaya, en el extremo occidental del Departamento de Oruro. Región de alta biodiversidad con acceso a las reservas naturales del altiplano chileno-boliviano.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3700,
    lat: -19.0,
    lng: -68.4,
    latStr: "19° 0' Sur",
    lngStr: "68° 24' Oeste",
    codigo: '040901',
    provincia: 'Sabaya',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Sabaya',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '310 km' },
    ],
    vecinos: [
      { nombre: 'Chipaya', dist: '60 km' }, { nombre: 'Coipasa', dist: '50 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '310 km', closest: true }, { nombre: 'Iquique (Chile)', km: '240 km' },
    ],
    idiomas: [],
  },

  // ─── POOPÓ ─────────────────────────────────────────
  {
    slug: 'poopo',
    nombre: 'Poopó',
    gentilicio: 'Poopeño/a',
    descripcion: 'Municipio de la Provincia Poopó, ubicado a orillas del histórico Lago Poopó. Centro minero y pesquero del altiplano central del Departamento de Oruro.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3720,
    lat: -18.3667,
    lng: -66.95,
    latStr: "18° 22' Sur",
    lngStr: "66° 57' Oeste",
    codigo: '040301',
    provincia: 'Poopó',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Poopó',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '30 km' },
    ],
    vecinos: [
      { nombre: 'Oruro', dist: '27 km' }, { nombre: 'Machacamarca', dist: '20 km' },
      { nombre: 'Antequera', dist: '25 km' }, { nombre: 'Huanuni', dist: '26 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '27 km', closest: true }, { nombre: 'Cochabamba', km: '150 km' },
    ],
    idiomas: [],
  },

  // ─── PAZÑA ─────────────────────────────────────────
  {
    slug: 'pazna',
    nombre: 'Pazña',
    gentilicio: 'Pazñeño/a',
    descripcion: 'Municipio de la Provincia Poopó, conocido por su tradición minera y sus comunidades indígenas. Localidad de gran riqueza cultural en el altiplano central de Oruro.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3700,
    lat: -18.5833,
    lng: -66.9333,
    latStr: "18° 35' Sur",
    lngStr: "66° 56' Oeste",
    codigo: '040302',
    provincia: 'Poopó',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Pazña',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '70 km' },
    ],
    vecinos: [
      { nombre: 'Huanuni', dist: '35 km' }, { nombre: 'Challapata', dist: '37.7 km' },
      { nombre: 'Poopó', dist: '20 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '65 km', closest: true }, { nombre: 'Potosí', km: '150 km' },
    ],
    idiomas: [],
  },

  // ─── HUAYLLAMARCA ──────────────────────────────────
  {
    slug: 'huayllamarca',
    nombre: 'Huayllamarca',
    gentilicio: 'Huayllamarcano/a',
    descripcion: 'Municipio de la Provincia Sajama, localidad del altiplano norte-occidental de Oruro. Comunidad vinculada a las rutas de conexión con el departamento de La Paz.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3760,
    lat: -17.9,
    lng: -68.0,
    latStr: "17° 54' Sur",
    lngStr: "68° 0' Oeste",
    codigo: '041001',
    provincia: 'Sajama',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Huayllamarca',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '180 km' },
    ],
    vecinos: [
      { nombre: 'Turco', dist: '50 km' }, { nombre: 'Curahuara de Carangas', dist: '60 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '180 km', closest: true }, { nombre: 'La Paz', km: '220 km' },
    ],
    idiomas: [],
  },

  // ─── EUCALIPTUS ────────────────────────────────────
  {
    slug: 'eucaliptus',
    nombre: 'Eucaliptus',
    gentilicio: 'Eucalipteño/a',
    descripcion: 'Municipio de la Provincia Cercado, localidad agrícola al norte del Departamento de Oruro. Comunidad conocida por sus cultivos y actividades ganaderas.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3750,
    lat: -17.5,
    lng: -67.1,
    latStr: "17° 30' Sur",
    lngStr: "67° 6' Oeste",
    codigo: '040105',
    provincia: 'Cercado',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Eucaliptus',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '55 km' },
    ],
    vecinos: [
      { nombre: 'Caracollo', dist: '35 km' }, { nombre: 'Oruro', dist: '55 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '55 km', closest: true }, { nombre: 'La Paz', km: '200 km' },
    ],
    idiomas: [],
  },

  // ─── SANTIAGO DE ANDAMARCA ─────────────────────────
  {
    slug: 'santiago-de-andamarca',
    nombre: 'Santiago de Andamarca',
    gentilicio: 'Andamarcano/a',
    descripcion: 'Municipio de la Provincia Sud Carangas, en el altiplano sur-occidental del Departamento de Oruro. Comunidad con fuerte identidad indígena y tradición cultural andina.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3820,
    lat: -18.9,
    lng: -67.4,
    latStr: "18° 54' Sur",
    lngStr: "67° 24' Oeste",
    codigo: '040801',
    provincia: 'Sud Carangas',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Santiago de Andamarca',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '180 km' },
    ],
    vecinos: [
      { nombre: 'Turco', dist: '60 km' }, { nombre: 'Corque', dist: '70 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '180 km', closest: true }, { nombre: 'Uyuni', km: '220 km' },
    ],
    idiomas: [],
  },

  // ─── TURCO ─────────────────────────────────────────
  {
    slug: 'turco',
    nombre: 'Turco',
    gentilicio: 'Turqueño/a',
    descripcion: 'Municipio de la Provincia Sajama, en el altiplano occidental de Oruro. Localidad próxima al Parque Nacional Sajama y al volcán activo más alto del mundo.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3740,
    lat: -18.1667,
    lng: -68.1833,
    latStr: "18° 10' Sur",
    lngStr: "68° 11' Oeste",
    codigo: '041002',
    provincia: 'Sajama',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Turco',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '220 km' },
    ],
    vecinos: [
      { nombre: 'Corque', dist: '45 km' }, { nombre: 'Huayllamarca', dist: '50 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '220 km', closest: true }, { nombre: 'La Paz', km: '250 km' },
    ],
    idiomas: [],
  },

  // ─── MACHACAMARCA ──────────────────────────────────
  {
    slug: 'machacamarca',
    nombre: 'Machacamarca',
    gentilicio: 'Machacamarcano/a',
    descripcion: 'Municipio de la Provincia Pantaleón Dalence, importante nodo ferroviario histórico del altiplano boliviano. Localidad con fuerte historia vinculada al ferrocarril.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3660,
    lat: -18.1667,
    lng: -66.85,
    latStr: "18° 10' Sur",
    lngStr: "66° 51' Oeste",
    codigo: '040702',
    provincia: 'Pantaleón Dalence',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Machacamarca',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '26 km' },
    ],
    vecinos: [
      { nombre: 'Oruro', dist: '25 km' }, { nombre: 'Poopó', dist: '20 km' },
      { nombre: 'Huanuni', dist: '23 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '25 km', closest: true }, { nombre: 'Cochabamba', km: '145 km' },
    ],
    idiomas: [],
  },

  // ─── ESCARA ────────────────────────────────────────
  {
    slug: 'escara',
    nombre: 'Escara',
    gentilicio: 'Escareño/a',
    descripcion: 'Municipio de la Provincia Carangas. Localidad del altiplano occidental del Departamento de Oruro, con economía basada en la ganadería de camélidos y agricultura.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3800,
    lat: -18.45,
    lng: -67.95,
    latStr: "18° 27' Sur",
    lngStr: "67° 57' Oeste",
    codigo: '040602',
    provincia: 'Carangas',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Escara',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '160 km' },
    ],
    vecinos: [
      { nombre: 'Corque', dist: '40 km' }, { nombre: 'Carangas', dist: '30 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '160 km', closest: true }, { nombre: 'La Paz', km: '280 km' },
    ],
    idiomas: [],
  },

  // ─── CURAHUARA DE CARANGAS ─────────────────────────
  {
    slug: 'curahuara-de-carangas',
    nombre: 'Curahuara de Carangas',
    gentilicio: 'Curahuareño/a',
    descripcion: 'Municipio de la Provincia Sajama, puerta de acceso al Parque Nacional Sajama. Destino turístico por su cercanía al Volcán Sajama (6,542 m), el más alto de Bolivia.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3850,
    lat: -18.0,
    lng: -68.45,
    latStr: "18° 0' Sur",
    lngStr: "68° 27' Oeste",
    codigo: '041003',
    provincia: 'Sajama',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Curahuara de Carangas',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aerop. Internacional de El Alto (La Paz)', dist: '170 km' },
    ],
    vecinos: [
      { nombre: 'Turco', dist: '50 km' }, { nombre: 'Huayllamarca', dist: '60 km' },
    ],
    distancias: [
      { nombre: 'La Paz', km: '170 km', closest: true }, { nombre: 'Oruro', km: '280 km' },
    ],
    idiomas: [],
  },

  // ─── SANTUARIO DE QUILLACAS ────────────────────────
  {
    slug: 'santuario-de-quillacas',
    nombre: 'Santuario de Quillacas',
    gentilicio: 'Quillacano/a',
    descripcion: 'Municipio de la Provincia Eduardo Abaroa, famoso por el Santuario de la Virgen de Quillacas, uno de los más importantes centros de peregrinación del altiplano boliviano.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3680,
    lat: -19.25,
    lng: -66.8667,
    latStr: "19° 15' Sur",
    lngStr: "66° 52' Oeste",
    codigo: '040203',
    provincia: 'Eduardo Abaroa',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Quillacas',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '160 km' },
    ],
    vecinos: [
      { nombre: 'Challapata', dist: '41.7 km' }, { nombre: 'Pampa Aullagas', dist: '30 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '160 km', closest: true }, { nombre: 'Potosí', km: '180 km' },
    ],
    idiomas: [],
  },

  // ─── ANTEQUERA ─────────────────────────────────────
  {
    slug: 'antequera',
    nombre: 'Antequera',
    gentilicio: 'Antequerano/a',
    descripcion: 'Municipio de la Provincia Poopó, localidad minera del altiplano central de Oruro. Comunidad con larga tradición en la explotación de recursos minerales del subsuelo boliviano.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3720,
    lat: -18.35,
    lng: -66.8,
    latStr: "18° 21' Sur",
    lngStr: "66° 48' Oeste",
    codigo: '040303',
    provincia: 'Poopó',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Antequera',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '50 km' },
    ],
    vecinos: [
      { nombre: 'Huanuni', dist: '21 km' }, { nombre: 'Machacamarca', dist: '25 km' },
      { nombre: 'Poopó', dist: '25 km' }, { nombre: 'Challapata', dist: '47.7 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '50 km', closest: true }, { nombre: 'Cochabamba', km: '150 km' },
    ],
    idiomas: [],
  },

  // ─── PAMPA AULLAGAS ────────────────────────────────
  {
    slug: 'pampa-aullagas',
    nombre: 'Pampa Aullagas',
    gentilicio: 'Aullagueño/a',
    descripcion: 'Municipio de la Provincia Eduardo Abaroa, localidad en el altiplano sur de Oruro. Relacionada históricamente con la mítica ciudad de Atlantis por algunos investigadores.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3700,
    lat: -19.3833,
    lng: -66.8333,
    latStr: "19° 23' Sur",
    lngStr: "66° 50' Oeste",
    codigo: '040204',
    provincia: 'Eduardo Abaroa',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Pampa Aullagas',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '195 km' },
    ],
    vecinos: [
      { nombre: 'Challapata', dist: '44 km' }, { nombre: 'Santuario de Quillacas', dist: '30 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '195 km', closest: true }, { nombre: 'Uyuni', km: '120 km' },
    ],
    idiomas: [],
  },

  // ─── CRUZ DE MACHACAMARCA ──────────────────────────
  {
    slug: 'cruz-de-machacamarca',
    nombre: 'Cruz de Machacamarca',
    gentilicio: 'Crucino/a',
    descripcion: 'Municipio de la Provincia Poopó, pequeña localidad en el altiplano central del Departamento de Oruro. Comunidad agrícola con acceso a vías férreas históricas.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3680,
    lat: -18.23,
    lng: -66.8667,
    latStr: "18° 14' Sur",
    lngStr: "66° 52' Oeste",
    codigo: '040304',
    provincia: 'Poopó',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Cruz de Machacamarca',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '30 km' },
    ],
    vecinos: [
      { nombre: 'Machacamarca', dist: '10 km' }, { nombre: 'Poopó', dist: '15 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '30 km', closest: true }, { nombre: 'Cochabamba', km: '150 km' },
    ],
    idiomas: [],
  },

  // ─── HUACHACALLA ───────────────────────────────────
  {
    slug: 'huachacalla',
    nombre: 'Huachacalla',
    gentilicio: 'Huachacalleño/a',
    descripcion: 'Municipio de la Provincia Sabaya, en el altiplano occidental del Departamento de Oruro. Localidad cerca del Salar de Coipasa, rica en recursos naturales y fauna altiplánica.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3680,
    lat: -18.8,
    lng: -68.2333,
    latStr: "18° 48' Sur",
    lngStr: "68° 14' Oeste",
    codigo: '040902',
    provincia: 'Sabaya',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Huachacalla',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '300 km' },
    ],
    vecinos: [
      { nombre: 'Sabaya', dist: '55 km' }, { nombre: 'Coipasa', dist: '40 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '300 km', closest: true }, { nombre: 'Iquique (Chile)', km: '260 km' },
    ],
    idiomas: [],
  },

  // ─── COIPASA ───────────────────────────────────────
  {
    slug: 'coipasa',
    nombre: 'Coipasa',
    gentilicio: 'Coipaseño/a',
    descripcion: 'Municipio de la Provincia Sabaya, ubicado junto al Salar de Coipasa. Región con ecosistemas únicos de humedales y salares, hogar de flamencos y otras aves migratorias.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3670,
    lat: -19.3,
    lng: -68.1167,
    latStr: "19° 18' Sur",
    lngStr: "68° 7' Oeste",
    codigo: '040903',
    provincia: 'Sabaya',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Coipasa',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '340 km' },
    ],
    vecinos: [
      { nombre: 'Sabaya', dist: '50 km' }, { nombre: 'Huachacalla', dist: '40 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '340 km', closest: true }, { nombre: 'Uyuni', km: '150 km' },
    ],
    idiomas: [],
  },

  // ─── CARANGAS ──────────────────────────────────────
  {
    slug: 'carangas',
    nombre: 'Carangas',
    gentilicio: 'Carangeño/a',
    descripcion: 'Municipio de la Provincia Carangas, corazón histórico del antiguo señorío de los Carangas. Rica herencia cultural precolombina en el altiplano occidental de Oruro.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3760,
    lat: -18.55,
    lng: -67.7833,
    latStr: "18° 33' Sur",
    lngStr: "67° 47' Oeste",
    codigo: '040603',
    provincia: 'Carangas',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Carangas',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '160 km' },
    ],
    vecinos: [
      { nombre: 'Corque', dist: '40 km' }, { nombre: 'Escara', dist: '30 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '160 km', closest: true }, { nombre: 'La Paz', km: '290 km' },
    ],
    idiomas: [],
  },

  // ─── CHIPAYA ───────────────────────────────────────
  {
    slug: 'chipaya',
    nombre: 'Chipaya',
    gentilicio: 'Chipaya',
    descripcion: 'Municipio de la Provincia Sabaya, hogar del pueblo Chipaya, una de las etnias más antiguas de América. Los Chipayas poseen una cultura, idioma y arquitectura únicos en el mundo.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3660,
    lat: -19.0833,
    lng: -68.25,
    latStr: "19° 5' Sur",
    lngStr: "68° 15' Oeste",
    codigo: '040904',
    provincia: 'Sabaya',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Chipaya',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '330 km' },
    ],
    vecinos: [
      { nombre: 'Sabaya', dist: '60 km' }, { nombre: 'Coipasa', dist: '45 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '330 km', closest: true }, { nombre: 'Iquique (Chile)', dist: '250 km' },
    ],
    idiomas: [{ lang: 'Chipaya (propio)', name: 'Chipaya' }],
  },

  // ─── TODOS SANTOS ──────────────────────────────────
  {
    slug: 'todos-santos',
    nombre: 'Todos Santos',
    gentilicio: 'Santino/a',
    descripcion: 'Municipio de la Provincia Sud Carangas, en el altiplano sur-occidental del Departamento de Oruro. Localidad de tradición pastoril con paisajes únicos del altiplano andino.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3850,
    lat: -19.15,
    lng: -67.65,
    latStr: "19° 9' Sur",
    lngStr: "67° 39' Oeste",
    codigo: '040802',
    provincia: 'Sud Carangas',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Todos Santos',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '200 km' },
    ],
    vecinos: [
      { nombre: 'Santiago de Andamarca', dist: '35 km' }, { nombre: 'Corque', dist: '60 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '200 km', closest: true }, { nombre: 'Uyuni', km: '250 km' },
    ],
    idiomas: [],
  },

  // ─── SORACACHI ─────────────────────────────────────
  {
    slug: 'soracachi',
    nombre: 'Soracachi',
    gentilicio: 'Soracacheño/a',
    descripcion: 'Municipio de la Provincia Cercado, vecino inmediato a la ciudad de Oruro. Comunidad agrícola del altiplano central con estrecha relación económica y cultural con la capital departamental.',
    esCapital: false,
    poblacion: 'N/D',
    anoCenso: 2012,
    rankingDep: 'N/D',
    altitud: 3700,
    lat: -17.85,
    lng: -67.0167,
    latStr: "17° 51' Sur",
    lngStr: "67° 1' Oeste",
    codigo: '040106',
    provincia: 'Cercado',
    alcalde: 'N/D',
    partido: 'N/D',
    direccion: 'Plaza Principal de Soracachi',
    telefono: 'N/D',
    web: null,
    ciudadesHermanadas: [],
    aeropuertos: [
      { nombre: 'Aeropuerto Juan Mendoza (Oruro)', dist: '25 km' },
    ],
    vecinos: [
      { nombre: 'Oruro', dist: '23.7 km' }, { nombre: 'Machacamarca', dist: '20 km' },
      { nombre: 'El Choro', dist: '25 km' },
    ],
    distancias: [
      { nombre: 'Oruro', km: '24 km', closest: true }, { nombre: 'Cochabamba', km: '135 km' },
    ],
    idiomas: [],
  },
];

export function getMunicipio(slug) {
  return municipios.find((m) => m.slug === slug) || null;
}
