-- ============================================================
-- PROYECTO: UP REACTIVA TIC (VERSIÓN POSTGRESQL / SUPABASE)
-- BASE DE DATOS: up_reactiva_tic (integrado en public schema)
-- DESCRIPCIÓN: Sistema de registro de emprendedores y empresas
-- AUTOR: Equipo de Datos (Adaptado para Supabase)
-- ============================================================

-- Habilitar extensión para actualizar timestamps automáticamente
CREATE EXTENSION IF NOT EXISTS moddatetime SCHEMA extensions;

-- ============================================================
-- SECCIÓN 1: CATÁLOGOS MAESTROS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.rubro (
    id_rubro        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rubro    VARCHAR(60) NOT NULL UNIQUE,
    descripcion     VARCHAR(200) NULL,
    activo          BOOLEAN DEFAULT TRUE,
    fecha_creacion  TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
CREATE INDEX IF NOT EXISTS idx_rubro_nombre ON public.rubro (nombre_rubro);

CREATE TABLE IF NOT EXISTS public.capacitacion (
    id_capacitacion      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_capacitacion  VARCHAR(180) NOT NULL UNIQUE,
    area                 VARCHAR(80) NULL,
    activo               BOOLEAN DEFAULT TRUE,
    fecha_creacion       TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
CREATE INDEX IF NOT EXISTS idx_cap_nombre ON public.capacitacion (nombre_capacitacion);
CREATE INDEX IF NOT EXISTS idx_cap_area ON public.capacitacion (area);

CREATE TABLE IF NOT EXISTS public.ubicacion (
    id_ubicacion    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio       VARCHAR(100) NOT NULL,
    zona            VARCHAR(120) NULL,
    direccion       VARCHAR(220) NULL,
    referencia      VARCHAR(220) NULL,
    transporte      VARCHAR(150) NULL,
    latitud         DECIMAL(10,7) NULL,
    longitud        DECIMAL(10,7) NULL,
    fecha_creacion  TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
CREATE INDEX IF NOT EXISTS idx_ubi_municipio ON public.ubicacion (municipio);
CREATE INDEX IF NOT EXISTS idx_ubi_zona ON public.ubicacion (zona);

CREATE TABLE IF NOT EXISTS public.formacion (
    id_formacion    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(40) NOT NULL UNIQUE,
    orden           INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.estado_civil (
    id_estado_civil INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.motivo_emprendimiento (
    id_motivo       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.rango_capacidad (
    id_rango        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion     VARCHAR(20) NOT NULL UNIQUE,
    orden           INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.rango_trabajadores (
    id_rango_trab   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion     VARCHAR(20) NOT NULL UNIQUE,
    orden           INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.tipo_participacion (
    id_participacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.familiar_involucrado (
    id_familiar     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.rol_emprendimiento (
    id_rol          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(40) NOT NULL UNIQUE
);

-- ============================================================
-- SECCIÓN 2: TABLAS PRINCIPALES
-- ============================================================

CREATE TABLE IF NOT EXISTS public.persona (
    id_persona          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dip                 VARCHAR(20) NULL UNIQUE,
    nombre_completo     VARCHAR(160) NOT NULL,
    celular             VARCHAR(25) NULL,
    celular_2           VARCHAR(25) NULL,
    id_formacion        INT REFERENCES public.formacion(id_formacion) ON UPDATE CASCADE ON DELETE SET NULL,
    id_estado_civil     INT REFERENCES public.estado_civil(id_estado_civil) ON UPDATE CASCADE ON DELETE SET NULL,
    num_hijos           INT DEFAULT 0,
    observaciones       TEXT NULL,
    fecha_registro      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    activo              BOOLEAN DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_persona_nombre ON public.persona (nombre_completo);
CREATE INDEX IF NOT EXISTS idx_persona_celular ON public.persona (celular);

-- Trigger para auto-actualizar fecha_actualizacion
CREATE TRIGGER handle_updated_at_persona
    BEFORE UPDATE ON public.persona
    FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime (fecha_actualizacion);

CREATE TABLE IF NOT EXISTS public.empresa (
    id_empresa              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_empresa          VARCHAR(160) NOT NULL,
    nit                     VARCHAR(20) NULL,
    usa_banca_movil         BOOLEAN DEFAULT FALSE,
    fecha_apertura          DATE NULL,
    fecha_registro          DATE NULL,
    servicios               TEXT NULL,
    id_rango_capacidad      INT REFERENCES public.rango_capacidad(id_rango) ON UPDATE CASCADE ON DELETE SET NULL,
    id_motivo               INT REFERENCES public.motivo_emprendimiento(id_motivo) ON UPDATE CASCADE ON DELETE SET NULL,
    id_rubro                INT REFERENCES public.rubro(id_rubro) ON UPDATE CASCADE ON DELETE SET NULL,
    id_ubicacion            INT REFERENCES public.ubicacion(id_ubicacion) ON UPDATE CASCADE ON DELETE SET NULL,
    observaciones           TEXT NULL,
    fecha_creacion          TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    fecha_actualizacion     TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    activo                  BOOLEAN DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_empresa_nombre ON public.empresa (nombre_empresa);
CREATE INDEX IF NOT EXISTS idx_empresa_nit ON public.empresa (nit);
CREATE INDEX IF NOT EXISTS idx_empresa_rubro ON public.empresa (id_rubro);
CREATE INDEX IF NOT EXISTS idx_empresa_ubicacion ON public.empresa (id_ubicacion);

CREATE TRIGGER handle_updated_at_empresa
    BEFORE UPDATE ON public.empresa
    FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime (fecha_actualizacion);

-- ============================================================
-- SECCIÓN 3: TABLAS DE RELACIÓN (N:M)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.emprendimiento_persona (
    id_emprendimiento   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona          INT NOT NULL REFERENCES public.persona(id_persona) ON UPDATE CASCADE ON DELETE CASCADE,
    id_empresa          INT NOT NULL REFERENCES public.empresa(id_empresa) ON UPDATE CASCADE ON DELETE CASCADE,
    id_rol              INT NULL REFERENCES public.rol_emprendimiento(id_rol) ON UPDATE CASCADE ON DELETE SET NULL,
    id_participacion    INT NULL REFERENCES public.tipo_participacion(id_participacion) ON UPDATE CASCADE ON DELETE SET NULL,
    id_rango_trab       INT NULL REFERENCES public.rango_trabajadores(id_rango_trab) ON UPDATE CASCADE ON DELETE SET NULL,
    es_titular          BOOLEAN DEFAULT FALSE,
    fecha_vinculacion   DATE NULL,
    fecha_creacion      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    activo              BOOLEAN DEFAULT TRUE,
    UNIQUE (id_persona, id_empresa)
);
CREATE INDEX IF NOT EXISTS idx_ep_persona ON public.emprendimiento_persona (id_persona);
CREATE INDEX IF NOT EXISTS idx_ep_empresa ON public.emprendimiento_persona (id_empresa);

CREATE TABLE IF NOT EXISTS public.empresa_capacitacion (
    id_empresa_cap      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa          INT NOT NULL REFERENCES public.empresa(id_empresa) ON UPDATE CASCADE ON DELETE CASCADE,
    id_capacitacion     INT NOT NULL REFERENCES public.capacitacion(id_capacitacion) ON UPDATE CASCADE ON DELETE CASCADE,
    fecha_capacitacion  DATE NULL,
    observaciones       VARCHAR(220) NULL,
    fecha_creacion      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE (id_empresa, id_capacitacion)
);
CREATE INDEX IF NOT EXISTS idx_ec_empresa ON public.empresa_capacitacion (id_empresa);
CREATE INDEX IF NOT EXISTS idx_ec_capacitacion ON public.empresa_capacitacion (id_capacitacion);

CREATE TABLE IF NOT EXISTS public.composicion_familiar (
    id_composicion      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_emprendimiento   INT NOT NULL REFERENCES public.emprendimiento_persona(id_emprendimiento) ON UPDATE CASCADE ON DELETE CASCADE,
    id_familiar         INT NOT NULL REFERENCES public.familiar_involucrado(id_familiar) ON UPDATE CASCADE ON DELETE CASCADE,
    apoya               BOOLEAN DEFAULT TRUE,
    observaciones       VARCHAR(220) NULL,
    fecha_creacion      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE (id_emprendimiento, id_familiar)
);
CREATE INDEX IF NOT EXISTS idx_cf_emprendimiento ON public.composicion_familiar (id_emprendimiento);

-- ============================================================
-- SECCIÓN 4: TABLAS DE AUDITORÍA (SUPABASE EDITION)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.log_cambios (
    id_log          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada  VARCHAR(60) NOT NULL,
    id_registro     INT NOT NULL,
    accion          VARCHAR(20) NOT NULL, -- INSERT, UPDATE, DELETE
    usuario_uid     UUID NULL, -- Integra con Supabase Auth
    fecha_evento    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    estado_anterior JSONB NULL,
    estado_nuevo    JSONB NULL
);
CREATE INDEX IF NOT EXISTS idx_log_tabla ON public.log_cambios (tabla_afectada);

-- Funciones PL/pgSQL para triggers genéricos de auditoría
CREATE OR REPLACE FUNCTION audit_log_changes()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO public.log_cambios (tabla_afectada, id_registro, accion, usuario_uid, estado_anterior)
        VALUES (TG_TABLE_NAME, OLD.id_persona, 'DELETE', auth.uid(), row_to_json(OLD)::jsonb);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        -- Extrae el ID (Asume que la PK se llama id_persona o id_empresa)
        -- Para evitar fallos genéricos, este script es específico.
        INSERT INTO public.log_cambios (tabla_afectada, id_registro, accion, usuario_uid, estado_anterior, estado_nuevo)
        VALUES (TG_TABLE_NAME, NEW.id_persona, 'UPDATE', auth.uid(), row_to_json(OLD)::jsonb, row_to_json(NEW)::jsonb);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO public.log_cambios (tabla_afectada, id_registro, accion, usuario_uid, estado_nuevo)
        VALUES (TG_TABLE_NAME, NEW.id_persona, 'INSERT', auth.uid(), row_to_json(NEW)::jsonb);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- En PostgreSQL, los triggers genéricos requieren cuidado con la Primary Key.
-- Solo aplicamos auditoría detallada a Persona y Empresa (simplificado para este ejemplo).

CREATE OR REPLACE FUNCTION audit_log_empresa()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'UPDATE') THEN
        INSERT INTO public.log_cambios (tabla_afectada, id_registro, accion, usuario_uid, estado_anterior, estado_nuevo)
        VALUES (TG_TABLE_NAME, NEW.id_empresa, 'UPDATE', auth.uid(), row_to_json(OLD)::jsonb, row_to_json(NEW)::jsonb);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO public.log_cambios (tabla_afectada, id_registro, accion, usuario_uid, estado_nuevo)
        VALUES (TG_TABLE_NAME, NEW.id_empresa, 'INSERT', auth.uid(), row_to_json(NEW)::jsonb);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_persona_audit
    AFTER INSERT OR UPDATE ON public.persona
    FOR EACH ROW EXECUTE FUNCTION audit_log_changes();

CREATE TRIGGER trg_empresa_audit
    AFTER INSERT OR UPDATE ON public.empresa
    FOR EACH ROW EXECUTE FUNCTION audit_log_empresa();


-- ============================================================
-- SECCIÓN 5: CARGA DE CATÁLOGOS (SEED DATA)
-- ============================================================

INSERT INTO public.rubro (nombre_rubro, descripcion) VALUES
('ALIMENTOS',   'Producción y comercialización de alimentos'),
('TEXTIL',      'Confección y tejidos'),
('ARTESANIAS',  'Artesanías en general'),
('SERVICIOS',   'Servicios varios'),
('COMERCIO',    'Comercio minorista'),
('AGRICULTURA', 'Producción agropecuaria'),
('OTROS',       'Otros rubros no clasificados')
ON CONFLICT (nombre_rubro) DO NOTHING;

INSERT INTO public.formacion (nombre, orden) VALUES
('INICIAL', 1),
('PRIMARIA', 2),
('SECUNDARIA', 3),
('TECNICO', 4),
('LICENCIATURA', 5),
('POSGRADO', 6)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.estado_civil (nombre) VALUES
('SOLTERO(A)'), ('CASADO(A)'), ('VIUDO(A)'), ('CONVIVIENTE'), ('SEPARADO(A)'), ('DIVORCIADO(A)')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.motivo_emprendimiento (nombre) VALUES
('POR INFLUENCIA FAMILIAR'), ('POR EXPERIENCIA LABORAL'), ('POR LA DEMANDA DEL MERCADO'), ('POR DESPIDO DE TRABAJO'), ('OTRO')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.rango_capacidad (descripcion, orden) VALUES
('1 A 2', 1), ('3 A 5', 2), ('6 A 10', 3), ('11 A 15', 4), ('16 A 25', 5), ('26 A 50', 6), ('> 50', 7)
ON CONFLICT (descripcion) DO NOTHING;

INSERT INTO public.rango_trabajadores (descripcion, orden) VALUES
('1 A 2', 1), ('3 A 4', 2), ('7 A 8', 3), ('9 A 10', 4), ('10 A 11', 5), ('12 A MAS', 6)
ON CONFLICT (descripcion) DO NOTHING;

INSERT INTO public.tipo_participacion (nombre) VALUES
('NINGUNO'), ('LOCAL'), ('MUNICIPAL'), ('NACIONAL'), ('INTERNACIONAL')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.familiar_involucrado (nombre) VALUES
('HIJOS'), ('PADRES'), ('PAREJA'), ('HERMANOS'), ('PRIMOS'), ('OTROS')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.rol_emprendimiento (nombre) VALUES
('TITULAR'), ('SOCIO'), ('FAMILIAR'), ('DEPENDIENTE')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.capacitacion (nombre_capacitacion, area) VALUES
('CAPACITACION EN COCINA', 'ALIMENTOS'), ('REPOSTERIA', 'ALIMENTOS'), ('ESPECIALIZACION EN REPOSTERIA', 'ALIMENTOS'),
('MARKETING DIGITAL', 'GESTION'), ('VENTAS', 'GESTION'), ('CONTABILIDAD', 'GESTION'),
('TEJIDO A MAQUINA', 'TEXTIL'), ('MANEJO DE REDES SOCIALES', 'GESTION')
ON CONFLICT (nombre_capacitacion) DO NOTHING;

-- 9.1 Ubicaciones de ejemplo
INSERT INTO public.ubicacion (municipio, zona, direccion) VALUES
('HUANUNI', 'HUANUNI', 'HUANUNI - ZONA CORAZON DE JESUS'),
('PAZÑA', 'NORTE', 'URB. CALA CAJA MZ - X - H'),
('ORURO', 'SUD', 'V. GALVARRO, 12 DE OCTUBRE Y ARICA')
ON CONFLICT DO NOTHING;

-- ============================================================
-- SECCIÓN 6: VISTAS Y RLS
-- ============================================================

-- Vista General 
CREATE OR REPLACE VIEW public.v_emprendedores AS
SELECT
    p.id_persona,
    p.dip,
    p.nombre_completo,
    p.celular,
    f.nombre AS formacion,
    ec.nombre AS estado_civil,
    p.num_hijos,
    e.id_empresa,
    e.nombre_empresa,
    e.nit,
    (e.nit IS NOT NULL AND e.nit <> '') AS tiene_nit,
    e.usa_banca_movil,
    r.nombre_rubro AS rubro,
    u.municipio,
    u.zona,
    e.fecha_registro
FROM public.persona p
JOIN public.emprendimiento_persona ep ON ep.id_persona = p.id_persona
JOIN public.empresa e ON e.id_empresa = ep.id_empresa
LEFT JOIN public.formacion f ON f.id_formacion = p.id_formacion
LEFT JOIN public.estado_civil ec ON ec.id_estado_civil = p.id_estado_civil
LEFT JOIN public.rubro r ON r.id_rubro = e.id_rubro
LEFT JOIN public.ubicacion u ON u.id_ubicacion = e.id_ubicacion
WHERE p.activo = TRUE AND e.activo = TRUE;

-- Vista Agrupada para Gráficos
CREATE OR REPLACE VIEW public.v_empresas_stats AS
SELECT
    r.nombre_rubro,
    u.municipio,
    COUNT(e.id_empresa) AS total_empresas,
    SUM(CASE WHEN e.usa_banca_movil THEN 1 ELSE 0 END) AS con_banca_movil,
    SUM(CASE WHEN (e.nit IS NOT NULL AND e.nit <> '') THEN 1 ELSE 0 END) AS con_nit
FROM public.empresa e
JOIN public.rubro r ON r.id_rubro = e.id_rubro
JOIN public.ubicacion u ON u.id_ubicacion = e.id_ubicacion
WHERE e.activo = TRUE
GROUP BY r.nombre_rubro, u.municipio;

-- Habilitar RLS en las tablas
ALTER TABLE public.rubro ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.capacitacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ubicacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.formacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estado_civil ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.motivo_emprendimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rango_capacidad ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rango_trabajadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipo_participacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.familiar_involucrado ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rol_emprendimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.persona ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.empresa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emprendimiento_persona ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.empresa_capacitacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.composicion_familiar ENABLE ROW LEVEL SECURITY;

-- Crear políticas de lectura pública
CREATE POLICY "Lectura publica catalogo rubro" ON public.rubro FOR SELECT USING (true);
CREATE POLICY "Lectura publica catalogo capacitacion" ON public.capacitacion FOR SELECT USING (true);
CREATE POLICY "Lectura publica catalogo ubicacion" ON public.ubicacion FOR SELECT USING (true);
CREATE POLICY "Lectura publica catalogo formacion" ON public.formacion FOR SELECT USING (true);
CREATE POLICY "Lectura publica persona" ON public.persona FOR SELECT USING (activo = true);
CREATE POLICY "Lectura publica empresa" ON public.empresa FOR SELECT USING (activo = true);
CREATE POLICY "Lectura publica ep" ON public.emprendimiento_persona FOR SELECT USING (activo = true);

-- PROCEDIMIENTOS ALMACENADOS (POSTGRESQL FUNCTIONS)
-- Se han modificado para recibir IDs directamente (Mejor Práctica)

CREATE OR REPLACE FUNCTION public.sp_registrar_persona_v2(
    p_dip VARCHAR(20),
    p_nombre VARCHAR(160),
    p_celular VARCHAR(25),
    p_id_formacion INT,
    p_id_estado_civil INT,
    p_num_hijos INT
)
RETURNS INT AS $$
DECLARE
    new_id INT;
BEGIN
    INSERT INTO public.persona (dip, nombre_completo, celular, id_formacion, id_estado_civil, num_hijos)
    VALUES (p_dip, p_nombre, p_celular, p_id_formacion, p_id_estado_civil, COALESCE(p_num_hijos, 0))
    RETURNING id_persona INTO new_id;
    
    RETURN new_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
